cards/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from cards import views

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.IndexView.as_view(), name = 'index'),

    url(r'^card/(?P<slug>\w+)/$', views.view, name = 'view'),
    url(r'^create/(?P<template_id>[0-9]+)/$', views.create, name = 'create'),
    url(r'^add/$', views.add, name = 'add'),
    url(r'^image/$', views.image, name = 'image'),
    url(r'^artists/', views.IndexArtistView.as_view(), name = 'index_artist'),
    url(r'^artist/(?P<artist_id>[0-9]+)/$', views.artist, name = 'artist'),
)

urlpatterns += staticfiles_urlpatterns()

cards/models.py
from django.db import models
from collections import defaultdict
from constance import config
from paintstore.fields import ColorPickerField
import settings
import os
import hashlib

class Artist(models.Model):
    first_name = models.CharField(max_length = 55)
    last_name = models.CharField(max_length = 55)
    biography = models.TextField(blank = True)
    image = models.ImageField(upload_to = os.path.join(settings.BASE_DIR, 'media/artist'), blank = True)
    url = models.CharField(max_length = 144, blank = True)
    hometown = models.CharField(max_length = 144, blank = True, null = True)
    created_at = models.DateTimeField(auto_now_add = True, null = True)
    updated_at = models.DateTimeField(auto_now = True, null = True)

    def image_name(self):
        return settings.MEDIA_URL + 'artist/' + str(self.image).split('/')[-1]

    def __str__(self):
        return self.first_name + ' ' + self.last_name
    def __unicode__(self): #Python 2.x
        return self.first_name + ' ' + self.last_name

class Art(models.Model):
    name = models.CharField(max_length = 89)
    artist = models.ForeignKey(Artist, null = True, blank = True)
    image = models.ImageField(upload_to = os.path.join(settings.BASE_DIR, 'media/art'))
    year = models.IntegerField(blank = True, null = True)
    created_at = models.DateTimeField(auto_now_add = True, null = True)
    updated_at = models.DateTimeField(auto_now = True, null = True)

    def image_name(self):
        return settings.MEDIA_URL + 'art/' + str(self.image).split('/')[-1]

    class Meta:
        verbose_name_plural = 'art'
    def __str__(self):
        return self.name
    def __unicode__(self): #Python 2.x
        return self.name

class Person(models.Model):
    first_name = models.CharField(max_length = 55, blank = True)
    last_name = models.CharField(max_length = 55, blank = True)
    email = models.CharField(max_length = 89, blank = True)
    postal_code = models.CharField(max_length = 13, blank = True)
    mailing_list = models.BooleanField(default = False)
    referrer = models.CharField(max_length = 55, blank = True)
    created_at = models.DateTimeField(auto_now_add = True, null = True)
    updated_at = models.DateTimeField(auto_now = True, null = True)

    @classmethod
    def create_or_update(cls, data, who):
        try:
            person = Person.objects.get(email = data['email'])
        except Person.DoesNotExist:
            person = Person()
        if 'sender' in who:
            person.referrer = data['referrer']
            person.mailing_list = data['mailing_list']
            person.postal_code = data['postal_code']
        person.first_name = data['first_name']
        person.last_name = data['last_name']
        person.email = data['email']
        person.save()
        return person

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'

    def __str__(self):
        return self.first_name + ' ' + self.last_name
    def __unicode__(self): #Python 2.x
        return self.first_name + ' ' + self.last_name

class Font(models.Model):
    name = models.CharField(max_length = 34)
    font_file = models.FileField(upload_to = os.path.join(settings.BASE_DIR, 'media/fonts'), null = True, blank = True)

    def __str__(self):
        return self.name
    def __unicode__(self): #Python 2.x
        return self.name

class Template(models.Model):
    art = models.ForeignKey(Art)
    order = models.IntegerField(default = 0)
    x_coord = models.IntegerField(default = 0)
    y_coord = models.IntegerField(default = 0)
    max_width = models.IntegerField(default = 0)
    max_height = models.IntegerField(default = 0)
    text_color = ColorPickerField()
    font = models.ForeignKey(Font)
    font_size = models.CharField(max_length = 8)
    extra_image = models.ImageField(upload_to = os.path.join(settings.BASE_DIR, 'media/templates'), null = True, blank = True)
    published = models.BooleanField(default = True)
    created_at = models.DateTimeField(auto_now_add = True, null = True)
    updated_at = models.DateTimeField(auto_now = True, null = True)

    def homepage_image(self):
	image_location = str(self.art.image)
        return image_location.replace(settings.BASE_DIR, '')
    def image(self):
        image_location = self.full_path_image()
        return image_location.replace(settings.BASE_DIR, '')
    def full_path_image(self):
        if not self.extra_image == '':
	    return str(self.extra_image)
        return str(self.art.image)

    def artist(self):
        return self.art.artist
    def form_fields(self, string_fields):
        fields = string_fields.replace(' ', '').split(',')

        field_dict = {
            'sender': [],
            'recipient': [],
            'message': [],
        }

        for field in fields:
            field_split = field.split('_', 1)
            attribute = field_split.pop()
            if not field_split:
                field_dict[attribute] = True
            else:
                part = field_split.pop()
                field_dict[part].append(attribute)

        return field_dict

    def field_types(self):
        field_types = {
            'first_name': 'text', 
            'last_name': 'text', 
            'email': 'text', 
            'postal_code': 'text', 
            'referrer': 'hidden', 
            'mailing_list': 'checkbox', 
            'message': 'textarea', 
        }
        return field_types

    def field_labels(self):
        field_types = {
            'first_name': 'First Name', 
            'last_name': 'Last Name', 
            'email': 'Email', 
            'postal_code': 'Postal Code', 
            'mailing_list': 'Join Our Mailing List?', 
            'message': 'Message', 
        }
        return field_types

    def __str__(self):
        return self.art.name
    def __unicode__(self): #Python 2.x
        return self.art.name

class Card(models.Model):
    template = models.ForeignKey(Template, null = True)
    recipient = models.ForeignKey(Person, related_name = '+', null = True)
    sender = models.ForeignKey(Person, related_name = '+', null = True)
    slug = models.SlugField(max_length = 55)
    hashed_id = models.SlugField(max_length = 55, null = True)
    short_url = models.CharField(max_length = 55, null = True)
    message = models.TextField(null = True, blank = True)
    featured = models.BooleanField(default = False)
    created_at = models.DateTimeField(auto_now_add = True, null = True)
    updated_at = models.DateTimeField(auto_now = True, null = True)

    @classmethod
    def create(cls, request):
        sender_data = {'first_name': '', 'last_name': '', 'email': '', 'postal_code': '', 'mailing_list': False, 'referrer': ''}
        recipient_data = {'first_name': '', 'last_name': '', 'email': '', 'postal_code': '', 'mailing_list': False, 'referrer': ''}
        message = ''
        for field in request.POST:
            if 'sender_' in field:
                field_name = field.replace('sender_', '')
                sender_data[field_name] = request.POST.get(field)
            if 'recipient_' in field:
                field_name = field.replace('recipient_', '')
                recipient_data[field_name] = request.POST.get(field)
            if 'message' in field:
                message = request.POST.get(field)
        sender = Person.create_or_update(sender_data, 'sender')
        recipient = Person.create_or_update(recipient_data, 'recipient')

        card = Card()
        card.message = message 
        card.template = Template.objects.get(pk = request.POST.get('template'))
        card.hashed_id = request.POST.get('hash')
        card.sender = sender
        card.recipient = recipient
        card.save()
        hash_object = hashlib.md5(str(card.id).encode())
        card.slug = hash_object.hexdigest()
        card.save()
        return card
    
    def featured_cards(self):
        try:
            return Card.objects.get(featured=True)
        except Card.DoesNotExist:
            return False

    def __str__(self):
        return self.slug
    def __unicode__(self): #Python 2.x
        return self.slug

cards/views.py
from django.core.urlresolvers import reverse
from django.core.mail import send_mail
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render
from django.template import RequestContext
from django.utils.safestring import mark_safe
from cards.models import Art, Artist, Card, Template
from constance import config
from django.views import generic
from PIL import Image, ImageDraw, ImageFont
import settings
import hashlib
import os

def add(request):
    card = Card.create(request)
    url = reverse('view', kwargs = {'slug': card.slug}) + '?new=1'
    sender_subject = add_replace(card, config.EMAIL_SUBJECT_SENDER)
    sender_body = add_replace(card, config.EMAIL_BODY_SENDER)
    recipient_subject = add_replace(card, config.EMAIL_SUBJECT)
    recipient_body = add_replace(card, config.EMAIL_BODY)

    send_mail(recipient_subject, None, card.sender.email, [card.recipient.email], fail_silently = True, html_message = mark_safe(recipient_body))
    send_mail(sender_subject, None, card.sender.email, [card.sender.email], fail_silently = True, html_message = mark_safe(sender_body))
    return HttpResponseRedirect(url)

def add_replace(card, haystack):
    replace_fields = {
        'sender_first_name': card.sender.first_name,
        'recipient_first_name': card.recipient.first_name,
        'url': 'http://' + settings.DOMAIN + reverse('view', kwargs = {'slug': card.slug}),
        'image': 'http://' + settings.DOMAIN + settings.MEDIA_URL + 'cards/' + card.hashed_id + '.jpg',
    }
    if card.template.id == 6:
	replace_fields['image'] = str(card.template.art.image).replace(settings.BASE_DIR, 'http://' + settings.DOMAIN)
    
    for needle in replace_fields.keys():
	haystack = haystack.replace('{{'+needle+'}}', replace_fields[needle])
            
    return haystack

def artist(request, artist_id):
    try:
        artist = Artist.objects.get(pk = artist_id)
    except Card.DoesNotExist:
        raise Http404
    art = Art.objects.filter(artist_id = artist_id)
    art_ids = []
    for art_piece in art:
        art_ids.append(art_piece.id)
    templates = Template.objects.filter(pk__in = art_ids)
    return render(request, config.TEMPLATE + '/artist.html', {'artist': artist, 'templates': templates})

class IndexArtistView(generic.ListView):
    model = Template
    template_name = config.TEMPLATE + '/index_artist.html'

    def get_queryset(self):
        return Template.objects.order_by('order')

def create(request, template_id):
    try:
        template = Template.objects.get(pk = template_id)
    except Template.DoesNotExist:
        raise Http404
    fields = config.FORM_FIELDS.split(',')
    return render(request, config.TEMPLATE + '/create.html', {'template': template, 'fields': template.form_fields(config.FORM_FIELDS), 'required': template.form_fields(config.REQUIRED_FIELDS), 'types': template.field_types, 'labels': template.field_labels})

class IndexView(generic.ListView):
    model = Template
    template_name = config.TEMPLATE + '/index.html'

    def get_queryset(self):
        return Template.objects.order_by('order')[:config.NUM_CARDS]

def image(request): #Presses text to image
    message = str(request.GET.get('message'))
    if not message:
        message = ' '
    
    #Hashing the image name
    image_name = str(request.GET.get('template')) + '+' + message
    hash_object = hashlib.md5(str(image_name).encode())
    card_location = settings.MEDIA_ROOT + "/cards/" + hash_object.hexdigest() + ".jpg"

    template = Template.objects.get(pk = request.GET.get('template'))

    #Check to see if this image already exists
    if not os.path.exists(card_location): 
        txt2img(template.full_path_image(), card_location, message, template.text_color, template.font.font_file, int(template.font_size), int(template.x_coord), int(template.y_coord))

    return HttpResponse('<img src="' + settings.MEDIA_URL + 'cards/' + hash_object.hexdigest() + '.jpg"><input type="hidden" name="hash" value="' + hash_object.hexdigest() + '" template="' + str(request.GET.get('template')) + '" text="' + message + '">')

def txt2img(img_name, new_img_name, text, font_color, font_file, font_size, x_coord = 0, y_coord = 0, bg = "#ffffff"):
    fnt = ImageFont.truetype(font_file, font_size)
    lineWidth = 20
    img = Image.open(img_name)
    draw = ImageDraw.Draw(img)                     # setup to draw on the main image
    draw.text((x_coord, y_coord), text, font = fnt, fill = font_color)      # add some text to the main
    del draw 
    img.save(new_img_name, "JPEG", quality = 100)  

def view(request, slug):
    try:
        card = Card.objects.get(slug = slug)
    except Card.DoesNotExist:
        raise Http404

    new = False
    if request.GET.get('new'):
        new = True

    return render(request, config.TEMPLATE + '/view.html', {'card': card, 'url': request.build_absolute_uri(), 'media_url': settings.MEDIA_URL, 'config': config, 'new': new,})

cards/templates/radicards/artist.html
{% extends "radicards/base.html" %}

{% block title %}
    Artist Profile: {{ artist }}
{% endblock title %}

{% block content %}
    <div id="intro artist-{{ artist.id }}">
      <h2 class="artist-name">{{ artist }}</h2>
      <div style="" class="artist-image"><img src="{{ artist.image_name }}" border="0" class="artist-thumbs"></div>
      <div class="artist-bio">{{ artist.biography }}</div>
      <div class="artist-url"><a href="{{ artist.url }}">{{ artist.url }}</a></div>
    </div>

    <h3>Cards by this Artist</h3>
    <div class="row">
      {% for template in templates %}
      <div style="" class="col-xs-6 col-sm-4 col-md-3 template template-{{ template.id }}"><a href="{% url "create" template.id %}" title="{{ template.id }}"><img src="{{ template.image }}" border="0" class="card-thumbs">{{ template }}</a></div>
      {% endfor %}
{% endblock content %}

cards/templates/radicards/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ config.SITE_NAME }} || {% block title %}{{ config.TAGLINE }}{% endblock title %}</title>

    <!-- Bootstrap -->
    <link href="{% static "radicards/css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "radicards/css/bootstrap.icon-large.min.css" %}" rel="stylesheet">
    <link href="{% static "radicards/css/style.css" %}" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="{% static "radicards/js/html5shiv.js" %}"></script>
      <script src="{% static "radicards/js/respond.min.js" %}"></script>
    <![endif]-->
    <meta property="og:site_name" content="{{ config.SITE_NAME }}">
    <meta property="og:description" content= "{{ config.TAGLINE }}"> 
    <meta property="og:url" content="">
    <meta property="og:type" content="article">
    <meta name="twitter:site" content="">
    <meta name="twitter:domain" content="mamasday.org">
    <meta name="twitter:card" content="photo">
    <link rel="shortcut icon" type="image/x-icon" href="{% static "radicards/images/favicon.ico" %}">
    {% block og_tags %}
      <meta property="og:title" content="{{ config.TAGLINE }}">
      <meta property="og:type" content="article">
      <meta property="og:image" content= "">
      <meta name="twitter:card" content="photo">
      <meta name="twitter:title" content="{{ config.TAGLINE }}">
      <meta name="twitter:image:src" content="">
    {% endblock og_tags %}
  </head>
  <body>
    <div class="container">
      <div id="logo">
        <a href="/"><img src="{% static "radicards/images/logo.png" %}" alt="{{ config.SITE_NAME }}"></a>
      </div>  
      <nav class="navbar navbar-default" role="navigation">      
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          <div id="social">
            <img src="http://placehold.it/32x32&text=social" alt="social">
            <img src="http://placehold.it/32x32&text=social" alt="social">
          </div>      
            
          </div>
      
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <li><a href="#">Menu Item</a></li>
              <li><a href="#">Menu Item</a></li>
              <li><a href="#">Menu Item</a></li>
              <li><a href="#">Menu Item</a></li>
              <li><a href="#">Menu Item</a></li>
            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>
      <div id="content">
        {% block content %}{% endblock content %} 
      </div>

      <div id="footer">
        <span style="float: left;">{{ config.SITE_NAME }} &copy; {{ this_year }} {{ config.ORGANIZATION_NAME }}</span>
        {% if config.RD_CREDIT %}
          <span style="float: right;">Powered by <a href="http://radicaldesigns.org"><img src="{% static "radicards/images/credit.png" %}" border=0 alt="radicalDESIGNS" class="credit"></a></span>
        {% endif %}
      </div>
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static "radicards/js//jquery-2.1.1.min.js" %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static "radicards/js/bootstrap.min.js" %}"></script>
    {% block footer_scripts %}{% endblock footer_scripts %}
  </body>
</html>

cards/templates/radicards/create.html
{% extends "radicards/base.html" %}

{% load dictionary %}

{% block title %}
  Create card
{% endblock title %}

{% block content %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'add' %}" method="post">
{% csrf_token %}
<input type="hidden" name="template" value="{{ template.id }}">

<div id="input-fields">
  <div id="sender-fields">
    <h2>You</h2>
  {% for field in fields.sender %}
    <div class="form-field type-{{ types|keyvalue:field }}">
      <label for="sender_{{ field }}">{{ labels|keyvalue:field }}
        {% if field in required.sender %}
          *
        {% endif %}
      </label>
      <input type="{{ types|keyvalue:field }}" name="sender_{{ field }}" id="sender_{ field }}" 
        {% if field in required.sender %}
          required="required"
        {% endif %}
      />
    </div>
  {% endfor %}
  </div>

  <div id="recipient-fields">
    <h2>Your Friend</h2>
  {% for field in fields.recipient %}
    <div class="form-field type-{{ types|keyvalue:field }}">
      <label for="recipient_{{ field }}">{{ labels|keyvalue:field }}
        {% if field in required.recipient %}
          *
        {% endif %}
      </label>
      <input type="{{ types|keyvalue:field }}" name="recipient_{{ field }}" id="recipient_{ field }}" 
        {% if field in required.recipient %}
          required="required"
        {% endif %}
      />
    </div>
  {% endfor %}
  </div>

  {% if fields.message %}
    <div id="message-field" class="form-field type-textarea">
      <label for="message">Message
        {% if required.message %}
          *
        {% endif %}
      </label>
      <textarea name="message" id="message" 
        {% if required.message %}
          required="required"
        {% endif %}
      /></textarea>
    </div>
  {% endif %}

  <input type="submit" value="Send" class="btn"/>
</div>

<div id="card-preview">
  <img src="{{ template.image }}">
  <input type="hidden" name="hash" value="">
</div>

</form>
{% endblock content %}

{% block footer_scripts %}
<script>
  $('textarea[name="message"]').change(function() {update_card();});
  $(document).ready(function() {update_card();});

  function update_card() {
    $('#card-preview').load("/image?template={{ template.id }}&text=" + encodeURIComponent($('textarea[name="message"]').val()));
  }
</script>
{% endblock footer_scripts %}

cards/templates/radicards/index.html
{% extends "radicards/base.html" %}

{% block content %}
    <div id="intro">
      {{ config.INTRO | safe }}
    </div>

    <div class="row">
      {% for template in template_list %}
        <div style="" class="col-xs-6 col-sm-4 col-md-3 template template-{{ template.id }}"><a href="{% url "create" template.id %}" title="{{ template.id }}"><img src="{{ template.image }}" border="0" class="card-thumbs"></a></div>
      {% endfor %}
    </div>
{% endblock content %}

cards/templates/radicards/index_artist.html
{% extends "radicards/base.html" %}

{% block title %}
    Artist Profiles
{% endblock title %}

{% block content %}
    <div class="row">
      {% for artist in artist_list %}
        <div style="" class="col-xs-6 col-sm-4 col-md-3 artist artist-{{ artist.id }}"><a href="{% url "artist" artist.id %}" title="{{ artist }}"><img src="{{ artist.image_name }}" border="0" class="artist-thumbs"><br>{{ artist }}</a></div>
      {% endfor %}
    </div>
{% endblock content %}

cards/templates/radicards/view.html
{% extends "radicards/base.html" %}

{% load social_buttons %}

{% block title %}
  View Your Card
{% endblock title %}

{% block og_tags %}
    <meta property="og:title" content="A card for {{ card.recipient.first_name }}">
    <meta property="og:image" content= "{{ media_url }}/cards/{{ card.hashed_id }}.jpg">
    <meta name="twitter:title" content="{{ config.message }}">
    <meta name="twitter:image:src" content="{{ media_url }}/cards/{{ card.hashed_id }}.jpg">
{% endblock og_tags %}

{% block content %}
  <div id="row">
    <div style="float: left;" class=""><img src="{{ media_url }}/cards/{{ card.hashed_id }}.jpg" border="0" class="card-thumbs"></div>      
  </div>
  <div id="output-fields">
    <div id="tag">
      To: {{ card.recipient.first_name }} {{ card.recipient.last_name }}<br>
      From: {{ card.sender.first_name }} {{ card.sender.last_name }}
    </div>
    <hr width=80%>
    <div id="artist-credit">
      {{ card.template.art }}
      {% if card.template.art.artist %}
        by <a href="{% url "artist" card.template.art.artist.id %}">{{ card.template.art.artist }}</a>
      {% endif %}
    </div>
    <hr width=80%>
    <div id="share">
      Share this card:<br>
      {{ shares | render:url | safe }}
    </div>
  </div>
{% endblock content %}